/**
 * Code block copy button functionality
 * Adds copy-to-clipboard buttons to all code blocks generated by rehype-pretty-code
 */

// SVG icons
const COPY_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>`;

const CHECK_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>`;

/**
 * Create a copy button element
 */
function createCopyButton(): HTMLButtonElement {
  const button = document.createElement("button");
  button.className = "copy-button";
  button.setAttribute("aria-label", "Copy code");
  button.innerHTML = COPY_ICON;
  return button;
}

/**
 * Get the code text to copy from a code block figure
 */
function getCodeText(figure: HTMLElement): string {
  const codeElement = figure.querySelector("code");
  if (!codeElement) return "";

  // Get all line spans
  const lines = codeElement.querySelectorAll("[data-line]");
  if (lines.length === 0) {
    return codeElement.textContent || "";
  }

  // Extract text from each line, preserving structure
  const lineTexts = Array.from(lines).map((line) => {
    return line.textContent || "";
  });

  return lineTexts.join("\n");
}

/**
 * Copy code to clipboard with visual feedback
 */
async function copyCode(button: HTMLButtonElement, figure: HTMLElement) {
  const code = getCodeText(figure);

  try {
    await navigator.clipboard.writeText(code);

    // Visual feedback: change icon to check
    button.innerHTML = CHECK_ICON;
    button.classList.add("copied");
    button.setAttribute("aria-label", "Copied!");

    // Reset after 2 seconds
    setTimeout(() => {
      button.innerHTML = COPY_ICON;
      button.classList.remove("copied");
      button.setAttribute("aria-label", "Copy code");
    }, 2000);
  } catch (err) {
    console.error("Failed to copy code:", err);
  }
}

/**
 * Initialize copy buttons for all code blocks
 */
function initCodeBlocks() {
  const figures = document.querySelectorAll<HTMLElement>(
    "[data-rehype-pretty-code-figure]",
  );

  figures.forEach((figure) => {
    // Skip if button already exists
    if (figure.querySelector(".copy-button")) return;

    const button = createCopyButton();
    button.addEventListener("click", () => copyCode(button, figure));

    // Insert button as first child (will be positioned absolutely via CSS)
    figure.insertBefore(button, figure.firstChild);
  });
}

// Initialize on page load
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", initCodeBlocks);
} else {
  initCodeBlocks();
}

// Re-initialize on view transitions (for Astro)
document.addEventListener("astro:page-load", initCodeBlocks);
